name: Bug
description: Describe a bug outside of lastfix or vessel issues
title: "[BUG:] <title>"
labels: ["bug"]
body:
- type: dropdown
  id: VesselName
  attributes:
    label: Vessel Name (if applicable, otherwise leave blank)
    options:
    - Adie_Alden
    - Adventure
    - Alicia_Ann
    - BantryBay
    - Beast_of_Burden
    - Brooke_C
    - Charger
    - Christi_Caroline
    - Christy
    - Dawn_T
    - Debbie_Sue
    - Devocean
    - Donna_Marie
    - Dorcas_Anne
    - Dyrsten
    - Elizabeth_Katherine
    - Ellen_Diane
    - Excalibur
    - Finlander_I
    - Finlander_II
    - Flicka
    - Fremantle_Doctor
    - Happy_Trails
    - Hound_Dog
    - Illusion
    - Lady_Claire
    - Lady_Jane
    - Lady_Rebecca
    - Lery_Charles
    - Lina_Rose
    - Linda_Marie
    - Lisa_Ann_III
    - Mary_Elizabeth
    - Mary_K
    - Michelle_Jean_II
    - Miss_Lilly
    - Mister_G
    - Moragh_K
    - Mussel_Point
    - Mystic
    - Nathaniel_Lee
    - Nicole_Leigh
    - Proud_Mary
    - Resolve
    - Rolex
    - Rueby
    - Sao_Paulo
    - Tenacious_II
    - Terri_Ann
    - Tina_Marie
    - Tom_Slaughter
    - Tribiah_Lee
    - Virginia_Marie
    - Virginia_Marise
    - Wendy_Lee
- type: dropdown
  id: Category
  attributes:
    label: Bug Category
    options:
    - Data Processing
    - Data Storage
    - Deck Box Software
    - Hardware
    - Vessel Troubleshooting
    - Website
  validations:
    required: true
- type: input
  id: DateObserved
  attributes:
    label: Date Observed
    placeholder: YYYY-MM-DD
  validations:
    required: true
- type: textarea
  id: symptom
  attributes:
    label: Description
    placeholder: Please describe the problem
- type: textarea
  id: potentialFix
  attributes:
    label: Potential Fix
    placeholder: If you have an idea to fix the problem, please include it here
